# -*- coding: utf-8 -*-
"""Lab6_Pawlak_Kamil_w69831.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bwl52dYEzRjsd0a792Ka1xMT3iT8GBPk
"""

import matplotlib.pyplot as plt
import numpy as np

threshold = 0.1
alpha = 0.1
x1 = [0,0,1,1]
x2 = [0,1,0,1]
y_d = [0, 1, 1, 1]
epoch = 1
w1 = 0.1
w2 = -0.2
finished = False

errors_chart = []
weights_chart = []

while finished == False:
  e_count = 0
  print(f"\nEpoch {epoch}")
  print(f"Starting weights: w1={w1}, w2={w2}\n")
  for i in range(0,4):
    y_sum = x1[i]*w1 + x2[i]*w2 - threshold
    y_p = 1 if y_sum >= 0 else 0
    e = y_d[i] - y_p
    e_count = e_count + 1 if e==1 else e_count
    delta_w1 = alpha * x1[i] * e
    delta_w2 = alpha * x2[i] * e
    w1 = round(w1 + delta_w1, 3)
    w2 = round(w2 + delta_w2, 3)
    print(
            f"Sample {i}: x=({x1[i]},{x2[i]})  "
            f"y_sum={y_sum:.3f} → y_p={y_p}  "
            f"target={y_d[i]}  error={e}  "
            f"Δw1={delta_w1:.3f}, Δw2={delta_w2:.3f}  "
            f"new w1={w1:.3f}, new w2={w2:.3f}"
        )
  print("Error count for this epoch: "+ str(e_count))
  errors_chart.append(e_count)
  weights_chart.append((w1, w2))
  if e_count == 0:
    finished = True
    print("Finished at epoch: " + str(epoch))

    plt.figure()
    plt.plot(range(1, len(errors_chart) + 1), errors_chart)
    plt.title('Error count per epoch')
    plt.xlabel('Epoch')
    plt.ylabel('Error count')
    plt.show()

    plt.figure()

    x1_arr = np.array(x1)
    x2_arr = np.array(x2)
    y_arr = np.array(y_d)

    plt.scatter(x1_arr[y_arr == 0], x2_arr[y_arr == 0], marker='o', label='Class 0')
    plt.scatter(x1_arr[y_arr == 1], x2_arr[y_arr == 1], marker='x', label='Class 1')

    x_vals = np.array([0, 1])
    y_vals = (threshold - w1 * x_vals) / w2
    plt.plot(x_vals, y_vals)

    plt.title('Separability')
    plt.xlabel('x1')
    plt.ylabel('x2')
    plt.legend()
    plt.show()
  else:
    epoch = epoch + 1